spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch
    username: postgres
    password: password